apiVersion: v1
kind: Service
metadata:
  name: mongo-db-svc
  namespace: database
  labels:
    {{- include "db.labels" . | nindent 4 }}
spec:
  selector:
    app: mongo-db
  ports:
  - port: 27017
    targetPort: dbport