apiVersion: v1
kind: Service
metadata:
  name: mongo-db-svc
  namespace: database
  labels:
    module: database
    env: dev
spec:
  selector:
    app: mongo-db
  ports:
  - port: 27017
    targetPort: dbport
