apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-api
  namespace: admin
  labels:
    module: admin
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin-api
  template:
    metadata:
      labels:
        app: admin-api
        module: admin
        env: dev
    spec:
      containers:
      - name: admin-api
        image: harshsoni777/admin-api:v1
        resources:
          requests:
            cpu: "250m"
            memory: "1Gi"
          limits:
            cpu: "500m"
            memory: "2Gi"
        ports:
        - containerPort: 1026
          name: http
        env:
          - name: MONGO_URL
            valueFrom:
              secretKeyRef:
                name:  admin-api-secrets
                key:  connectionstring
          - name: PORT
            value: "1026"
        livenessProbe:
          httpGet:
            path: /api/health 
            port: 1026
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 1026
          initialDelaySeconds: 30
          timeoutSeconds: 10