apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-ui
  namespace: user
  labels:
    module: user
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-ui
  template:
    metadata:
      labels:
        app: user-ui
        module: user
        env: dev
    spec:
      containers:
      - name: user-ui
        image: harshsoni777/user-ui:v1
        resources:
          requests:
            cpu: "250m"
            memory: "1Gi"
          limits:
            cpu: "500m"
            memory: "2Gi"
        ports:
        - containerPort: 3000
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 3000
        #   initialDelaySeconds: 30
        #   timeoutSeconds: 5
        #   failureThreshold: 5
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 3000
        #   initialDelaySeconds: 30
        #   timeoutSeconds: 10
        volumeMounts:
        - name:  user-ui-vi
          mountPath:  /app/.env
          subPath: .env
      volumes:
      - name:  user-ui-vi
        configMap:
          name: user-ui-cm
    