# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  paths:
    include:
      - result/*

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '5aa32f76-931d-4400-bb47-35b97cd53396'
  imageRepository: 'resultapp'
  containerRegistry: 'harshazurecicd.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/result/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  #vmImageName: 'ubuntu-latest'
pool:
 name: 'azureagent'

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build 
    # This is for (worker node) which will work as Agent to run this pipeline, but its not provided in the free accounts as of now. So we donot need this right now.
    # pool:
    #   vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build the Image
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: 'result/Dockerfile'
        tags: '$(tag)'

- stage: Push
  displayName: Push
  jobs:
  - job: Push
    displayName: Push the Image
    # This is for (worker node) which will work as Agent to run this pipeline, but its not provided in the free accounts as of now. So we donot need this right now.
    # pool:
    #   vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Push the Image
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'push'
        tags: '$(tag)'