apps:
  replicas: 3
  env: qa
  computers:
    requests:
      cpu: "300m"
      memory: "1.5Gi"
    limits:
      cpu: "750m"
      memory: "4Gi"
  image: harshsoni777/user-ui:v1
  containerPort: 3000

hpa:
  enabled: false
  
service:
  port: 3000
  targetPort: 3000
  nodePort: 32005
  type: NodePort

volume:
  name: user-ui-vi #volume and volumeMount Name

configMap:
  name: user-ui-cm